run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - bodyclose
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gocritic

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
